[package]
name = "proof_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
risc0-zkp = {version = "1.0.1", default-features = false }
alloy-sol-types = "0.7.7"
alloy-primitives = "0.7.7"
